// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model;

public partial class Author
{
    [Key]
    public Guid Id { get; set; }

    public int NumId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Surname { get; set; }

    [InverseProperty("Author")]
    public virtual ICollection<DocumentsAuthor> DocumentsAuthors { get; } = new List<DocumentsAuthor>();
}