// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model;

public partial class DocumentsAuthor
{
    [Key]
    public Guid Id { get; set; }

    public int NumId { get; set; }

    public Guid DocumentId { get; set; }

    public Guid AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("DocumentsAuthors")]
    public virtual Author Author { get; set; }

    [ForeignKey("DocumentId")]
    [InverseProperty("DocumentsAuthors")]
    public virtual Document Document { get; set; }
}